{
    'name': 'Bookstore',
    'version': '19.0.1.4.2',
    'category': 'Retail',
    'depends': [
        'account',
        'base_automation',
        'delivery',
        'loyalty',
        'mail',
        'point_of_sale',
        'pos_loyalty',
        'product',
        'purchase',
        'sale_management',
        'stock',
        'website_sale',
        'website_sale_stock',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_default.xml',
        'data/res_config_settings.xml',
        'data/stock_warehouse.xml',
        'data/ir_ui_view.xml',
        'data/base_automation.xml',
        'data/ir_actions_server.xml',
        'data/product_pricelist.xml',
        'data/stock_collect.xml',
        'data/pos_payment_method.xml',
        'data/pos_config.xml',
        'data/loyalty_program_views.xml',
    ],

    'license': 'OEEL-1',
    'author': 'Odoo S.A., Harry Bird',
    'images': ['images/main.png'],
}
