{
    'name': 'Bookstore',
    'version': '1.15.14',
    'category': 'Retail',
    'depends': [
        'account',
        'account_followup',
        'accountant',
        'appointment',
        'calendar',
        'contacts',
        'delivery',
        'documents',
        'hr',
        'hr_attendance',
        'iot',
        'loyalty',
        'mail',
        'mass_mailing',
        'planning',
        'point_of_sale',
        'pos_discount',
        'pos_sale',
        'project',
        'project_todo',
        'purchase',
        'purchase_stock',
        'stock_picking_batch',
        'sale_management',
        'sale_purchase',
        'sign',
        'stock',
        'stock_account',
        'stock_barcode',
        'stock_barcode_barcodelookup',
        'vendor_returns',
        'web_studio',
        'website',
        'website_event',
        'website_sale',
        'website_sale_stock',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_default.xml',
        'data/res_config_settings.xml',
        'data/stock_warehouse.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/base_automation.xml',
        'data/ir_actions_server.xml',
        'data/product_pricelist.xml',
        'data/stock_collect.xml',
        'data/pos_payment_method.xml',
        'data/pos_config.xml',
        'data/loyalty_program_views.xml',
    ],
    "cloc_exclude": [
    ],
    'license': 'OEEL-1',
    'author': 'Odoo S.A., Harry Bird',
    'images': ['images/main.png'],
}
