{
    'name': 'Bookstore',
    'version': '1.13.2',
    'category': 'Retail',
    'depends': [
        'account',
        'account_followup',
        'accountant',
        'appointment',
        'calendar',
        'contacts',
        'delivery',
        'documents',
        'hr',
        'hr_attendance',
        'iot',
        'knowledge',
        'loyalty',
        'mail',
        'mass_mailing',
        'planning',
        'point_of_sale',
        'pos_discount',
        'pos_sale',
        'project',
        'project_todo',
        'purchase',
        'purchase_stock',
        'sale_management',
        'sale_purchase',
        'sign',
        'stock',
        'stock_account',
        'stock_barcode',
        'stock_barcode_barcodelookup',
        'web_studio',
        'website',
        'website_event',
        'website_sale',
        'website_sale_stock',
    ],
    'data': [
        'data/ir_default.xml',
        'data/res_config_settings.xml',
        'data/stock_warehouse.xml',
        'data/ir_attachment_pre.xml',
        'data/ir_model_fields.xml',
        'data/ir_ui_view.xml',
        'data/base_automation.xml',
        'data/ir_actions_server.xml',
        'data/pos_category.xml',
        'data/product_category.xml',
        'data/product_pricelist.xml',
        'data/product_product.xml',
        'data/stock_collect.xml',
        'data/pos_payment_method.xml',
        'data/pos_config.xml',
        'data/knowledge_cover.xml',
        'data/knowledge_article.xml',
        'data/knowledge_article_favorite.xml',
        'data/mail_message.xml',
        'data/knowledge_tour.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'bookstore/static/src/js/my_tour.js',
        ]
    },
    "cloc_exclude": [
        "data/knowledge_article.xml",
        "static/src/js/my_tour.js",
    ],
    'license': 'OEEL-1',
    'author': 'Odoo S.A., Harry Bird',
    'images': ['images/main.png'],
}
