{
    'name': 'Dependencies',
    'version': '1.0',
    'category': 'Retail',
    'depends': [
        'hr_attendance',
        'mass_mailing',
        'website',
        'documents',
        'calendar',
        'sign',
        'website_event',
        'accountant',
        'knowledge',
        'appointment',
        'hr',
        'project',
        'survey',
        'planning',
        'point_of_sale',
        'website_sale',
        'contacts',
        'hr_skills',
        'purchase',
        'stock_barcode',
        'stock',
        'project_todo',
        'iot',
        'account',
        'mail'
    ],
    
    'license': 'OEEL-1',
    'author': 'Harry Bird',
    'images': ['images/main.png']
}
