from . import loyalty_card
from . import loyalty_program
from . import product_product
from . import product_template
from . import sale_order
from . import stock_picking
from . import vendor_return_policy
from . import vendor_return_line
from . import vendor_return_order
