from . import book_author
from . import book_publisher
from . import book_product_author
from . import loyalty_card
from . import loyalty_program
from . import pos_order
from . import product_product
from . import product_public_category
from . import product_template
from . import purchase_order_line
from . import sale_order
from . import stock_warehouse_orderpoint
